'use client'

import './globals.css';
import Head from "next/head";
import MyNav from "./MyComponents/MyNav";
import { React } from "react"; 

import HomePage from "./MyComponents/HomePage";
import Projects from "./MyComponents/Projects";
import MyFooter from "./MyComponents/MyFooter";


export default function Home() {

  return (
      <div>
        <Head>
          <title>My personal website</title>
          <meta name='description' content='Generated by create' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main>
          <div className="scrollbar scrollbar-thumb-cyan-300 font-monrope">
            <section id="home" className="scroll-smooth"> 
              <div className="min-h-screen bg-gray-900"> 
                {/* Navigation Bar */}
                <MyNav />
                {/* Home Page */}
                <HomePage/>
              </div>
            </section>
            <section id="projects" className="scroll-smooth"> 
              <div className="min-h-screen bg-gray-900"> 
                {/* Projects */}
                <Projects />
              </div>
            </section>
            <section id="footer" className="scroll-smooth flex flex-col justify-end"> 
              <div className="bg-gray-900"> 
                {/* Footer */}
                <MyFooter mySize={45} />
              </div>
            </section>
          </div>
        </main>
      </div>
  );
}
