'use client'

import Image from "next/image";
import Head from "next/head";
import MyNav from "./MyComponents/MyNav";
import { React, useRef } from "react"; 

import HomePage from "./MyComponents/HomePage";
import MyFooter from "./MyComponents/MyFooter";
import AboutPage from "./MyComponents/AboutPage";

export default function Home() {


  // figure out smooth animation later
  // const navBar = useRef(null);
  // const aboutPage = useRef(null);
  // const resumePage = useRef(null);
  // const footerPage = useRef(null);

  return (
      <div>
        <Head>
          <title>My personal website</title>
          <meta name='description' content='Generated by create' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main>

          {/* Figure out how useRef works so you can implement the scrolling feature! */}

          {/* change to bg-gray-800 maybe */}
          <section className="min-h-screen bg-gray-900 font-monrope"> 

            {/* Nav bar */} 
            {/* bg-teal-500 */}
            <MyNav />
            {/* Home page */}
            <HomePage />

            {/* About page */}
            <AboutPage />

            {/* Footer */}
            <MyFooter />

          </section>
        </main>
      </div>
  );
}
