'use client'

import Image from "next/image";
import Head from "next/head";
import MyNav from "./MyComponents/MyNav";
import { React, useRef } from "react"; 

import FrontPage from "./MyComponents/FrontPage";
import MyFooter from "./MyComponents/MyFooter";

export default function Home() {


  // figure out scrolling logic latr
  const navBar = useRef(null);
  const aboutPage = useRef(null);
  const resumePage = useRef(null);
  const footerPage = useRef(null);

  return (
      <div>
        <Head>
          <title>My personal website</title>
          <meta name='description' content='Generated by create' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main>

          {/* Figure out how useRef works so you can implement the scrolling feature! */}

          {/* change to bg-gray-800 maybe */}
          <section className="min-h-screen font-manrope bg-gray-900"> 

            {/* CHANGE V = IR to an omega symbol when screen size becomes smaller! Also change buttons to 
                navigation icon later
            */}
            {/* Nav bar */} 
            {/* bg-teal-500 */}
            <MyNav ref={navBar} />
            {/* Front page */}
            <FrontPage ref={aboutPage} />

            {/* Footer */}
            <MyFooter />

          </section>
        </main>
        
         
      </div>
  );
}
